#!/usr/bin/env bash

set -e

if [[ "$1" == "uninstall" ]]; then
  pushd ~/projects/dotfiles
  stow -D -t ${HOME} {bash,curl,vim,git,screen}
  stow -D -t ${HOME}/.config --no-folding .config
  echo "Dotfiles uninstalled!"
  exit 0
fi

case "$(uname -s)" in
  "Darwin")
    brew install openssl pv curl direnv
    ;;
  "Linux")
    sudo apt-get update && sudo apt-get install -y curl feh xclip pv openssl direnv
    ;;
esac

mkdir -p ${HOME}/{projects,.config}

pushd ~/projects > /dev/null

if [[ ! -d "${HOME}/projects/dotfiles"  ]]; then
    ssh-keyscan github.com >> ~/.ssh/known_hosts
    git clone https://github.com/veerendra2/prepare-my-machine.git
fi

pushd dotfiles > /dev/null
git pull

touch bash/.extra .extra-gitconfig

stow -t ${HOME} {bash,curl,vim,git,screen}
stow -t ${HOME}/.config --no-folding .config
echo "Dotfiles installed!"
