#!/usr/bin/env bash

case "$(uname -s)" in
  "Darwin")
    brew install openssl pv curl direnv
    ;;
  "Linux")
    sudo apt-get update && sudo apt-get install -y curl feh xclip pv openssl direnv
    ;;
esac

mkdir -p ${HOME}/{projects,.config}

pushd ~/projects > /dev/null
git clone https://github.com/veerendra2/dotfiles.git

pushd dotfiles > /dev/null
git pull

touch bash/.extra .extra-gitconfig

stow {bash,curl,vim,git,screen}
stow --target "${HOME}/.config" --no-folding .config

# To uninstall
# stow -D .
