#!/usr/bin/env bash

if [ "$(uname -s)" == "Darwin" ]; then
	brew install yq ngrep openssl pv curl direnv
fi

if [ "$(uname -s)" == "Darwin" ]; then
	apt-get update && apt-get install curl feh xclip ngrep pv openssl direnv -y
  curl -qo /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 > /dev/null 2>&1
  chmod +x /usr/local/bin/yq
fi

mkdir -p ~/projects

pushd ~/projects > /dev/null
git clone https://github.com/veerendra2/dotfiles.git

pushd dotfiles > /dev/null
git pull

for file in $(find ${PWD} -name ".*" -not -name ".gitignore" -not -name ".git" -not -name ".config" -not -name ".github" -not -name ".*.swp" -not -name ".gnupg");
do
	f=$(basename $file);
	ln -sfn $file ${HOME}/$f;
done
