[settings]
experimental = true

dotfiles.root = "~/projects/dotfiles"
dotfiles.default_mode = "symlink"

[dotfiles]

############################
#          Shell           #
############################

"~/.bash_profile" = "shell/bash/.bash_profile"
"~/.bashrc" = "shell/bash/.bashrc"

"~/.zprofile" = "shell/zsh/.zprofile"
"~/.zshrc" = "shell/zsh/.zshrc"

"~/" = { source = "shell/common", mode = "symlink-each" }

############################
#           Core           #
############################

"~/.curlrc" = "tools/curl/.curlrc"
"~/.screenrc" = "tools/screen/.screenrc"
"~/.ssh/config" = "tools/ssh/config"

############################
#          Config          #
############################

"~/.claude" = { source = "tools/claude", mode = "symlink-each" }
"~/.config/direnv/direnv.toml" = "tools/direnv/direnv.toml"
"~/.config/ghostty" = { source = "tools/ghostty", mode = "symlink-each" }
"~/.config/git" = { source = "tools/git", mode = "symlink-each" }
"~/.config/k9s/hotkeys.yaml" = "tools/k9s/hotkeys.yaml"
"~/.config/mise/config.toml" = "tools/mise/config.toml"
"~/.config/navi/cheats" = { source = "tools/navi/cheats", mode = "symlink-each" }
"~/.config/navi/config.yaml" = "tools/navi/config.yaml"
"~/.config/opencode/opencode.json" = "tools/opencode/opencode.json"
"~/.config/rtk/config.toml" = "tools/rtk/config.toml"
"~/.config/starship/starship.toml" = "tools/starship/starship.toml"
