[settings]
experimental = true
dotfiles.root = "~/projects/dotfiles"
dotfiles.default_mode = "symlink"

[dotfiles]

############################
#          Shell           #
############################

"~/.aliases" = "shell/common/.aliases"
"~/.functions" = "shell/common/.functions"
"~/.exports" = "shell/common/.exports"
"~/.bashrc" = "shell/bash/.bashrc"
"~/.bash_profile" = "shell/bash/.bash_profile"
"~/.zshrc" = "shell/zsh/.zshrc"
"~/.zprofile" = "shell/zsh/.zprofile"

############################
#           Core           #
############################

"~/.curlrc" = "tools/curl/.curlrc"
"~/.gitconfig" = "tools/git/.gitconfig"
"~/.extra-gitconfig" = "tools/git/.extra-gitconfig"
"~/.screenrc" = "tools/screen/.screenrc"
"~/.ssh/config" = "tools/ssh/config"

############################
#          Config          #
############################

"~/.config/direnv/direnv.toml" = "tools/direnv/direnv.toml"
"~/.config/ghostty" = { source = "tools/ghostty", mode = "symlink-each" }
"~/.config/k9s/hotkeys.yaml" = "tools/k9s/hotkeys.yaml"
"~/.config/mise/config.toml" = "tools/mise/config.toml"
"~/.config/navi/config.yaml" = "tools/navi/config.yaml"
"~/.config/navi/cheats" = { source = "tools/navi/cheats", mode = "symlink-each" }
"~/.config/opencode/opencode.json" = "tools/opencode/opencode.json"
"~/.config/rtk/config.toml" = "tools/rtk/config.toml"
"~/.config/starship/starship.toml" = "tools/starship/starship.toml"

############################
#          Claude          #
############################

"~/.claude" = { source = "tools/claude", mode = "symlink-each" }
