############################
#       Development        #
############################

tap "hashicorp/tap"

brew "bitwarden-cli"     # Bitwarden CLI
brew "go"                # Go compiler and tools
brew "golangci-lint"     # Go linter runner
brew "hashicorp/tap/terraform" # Terraform CLI (HashiCorp Tap for ARM64 Linux support)
brew "kubecolor"         # Colorized kubectl output
brew "kubectx"           # Kubernetes context switcher
brew "kubernetes-cli"    # kubectl
brew "uv"                # Python package manager

############################
#        Utilities         #
############################

brew "starship"          # Cross-shell prompt
