"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$directory\
$shlvl\
$git_branch\
$git_status\
$kubernetes\
$terraform\
$python\
$nodejs\
$golang\
$rust\
$ruby\
$aws\
$azure\
$docker_context\
$vagrant\
$direnv\
$jobs\
$time\
$cmd_duration\
$line_break\
$character"""

add_newline = true

palette = "cusom"

[username]
format = '[$user]($style) at '

[hostname]
format = '[$hostname]($style) in '

[shlvl]
disabled = false
format = '[$symbol$shlvl]($style) '
symbol = " "
threshold = 3

[directory]
format = '[$path ]($style)[$read_only]($read_only_style)'
read_only = "󱪨 "
read_only_style = "red"
style = 'bold color_aqua'
truncate_to_repo = false
truncation_length = 3
truncation_symbol = '…/'

[directory.substitutions]
'Documents' = '󰈙'
'Downloads' = ' '
'Music' = ' '
'Pictures' = ' '
'projects' = ' '

[kubernetes]
format = '[$symbol$context\($namespace\)]($style) '
symbol = "󱃾 "
disabled = false
contexts = [
  { context_pattern = "^dev.*", style = "color_purple" },
  { context_pattern = "^stage.*", style = "color_orange" },
  { context_pattern = "^prod.*", style = "color_red" },
]

[git_branch]
format = '[on](white) [$symbol$branch ]($style)'
style = 'color_green'
symbol = ' '
truncation_length = 20
truncation_symbol = '…'

[git_status]
style = 'color_red_1'
format = '([$all_status$ahead_behind]($style) )'

[python]
format = '[${symbol}${pyenv_prefix}(${version})(\($virtualenv\) )]($style)'
pyenv_version_name = true
style = 'teal'
symbol = ' '

[nodejs]
style = 'blue'
symbol = ' '
format = "[$symbol($version )]($style)"

[golang]
style = 'blue'
symbol = ' '
format = "[$symbol($version )]($style)"

[rust]
style = 'orange'
symbol = ' '
format = "[$symbol($version )]($style)"

[ruby]
style = 'blue'
symbol = ' '
format = "[$symbol($version )]($style)"

[package]
symbol = '󰏗 '

[aws]
symbol = ' '
style = 'yellow'
format = '[$symbol($profile)]($style)'

[azure]
disabled = true
format = '$symbol($subscription) '
symbol = '󰠅 '

[terraform]
disabled = false
format = '[$symbol$version]($style) '
style = 'bold 105'
symbol = '󱁢 '

[docker_context]
detect_extensions = ['Dockerfile']
detect_files = [
  'docker-compose.yml',
  'docker-compose.yaml',
  'Dockerfile',
  'compose.yml',
  'compose.yaml',
]
disabled = false
format = '[$symbol]($style) '
only_with_files = true
style = 'fg:#06969A'
symbol = ' '

[jobs]
format = '[$symbol]($style)'
number_threshold = 1
style = 'red'
symbol = ' '

[time]
disabled = false
format = '[󱑒 $time]($style) '
time_format = '%T'
utc_time_offset = 'local'

[cmd_duration]
format = '[󱫍 $duration]($style)'
min_time = 500
style = "color_cyan"

[vagrant]
format = '[$symbol($version )]($style)'
symbol = ' '
version_format = 'v${raw}'

[direnv]
allowed_msg = ' '
denied_msg = ' '
disabled = false
loaded_msg = ' '
not_allowed_msg = '󰂭 '
style = "bright-yellow"
unloaded_msg = '󰿅 '

[character]
disabled = false
error_symbol = '[](bold fg:color_red)'
success_symbol = '[](bold fg:color_green)'

[os.symbols]
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
EndeavourOS = ""
Fedora = "󰣛"
Gentoo = "󰣨"
Linux = "󰌽"
Macos = "󰀵"
Manjaro = ""
Mint = "󰣭"
Pop = ""
Raspbian = "󰐿"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
SUSE = ""
Ubuntu = "󰕈"
Windows = "󰍲"

[palettes.cusom]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_red_1 = '#e06c75'
color_yellow = '#d79921'
color_cyan = '#56b6c2'
